# Generated by Django 2.1.2 on 2018-10-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='slug',
            field=models.CharField(default='Slug', max_length=50, verbose_name='Slug'),
        ),
    ]
